# Generated by Django 3.1.1 on 2020-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=1000)),
                ('about', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('github', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('dev_to', models.CharField(max_length=1000)),
            ],
        ),
    ]
