# Generated by Django 3.1.1 on 2020-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.CharField(default='www.google.com', max_length=200),
            preserve_default=False,
        ),
    ]
