# Generated by Django 3.1.1 on 2020-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('wd', 'Web Development'), ('ai', 'Artificial Intelligence'), ('da', 'Data Analysis')], default='wd', max_length=2),
        ),
    ]
